### ISSUE TITLE
Errore nel paragrafo SMTP

### ISSUE THREAD

**Issue by mirkomatonti** [Gethseman/Appunti-Reti-2019-20#1]
Ciao ho trovato un errore a pagina 49

> N.B. Il protocollo SMTP usa il protocollo di trasporto **FTP** per consegnare in maniera affidabile i messaggi.

> Apertura della connessione o handshaking con cui il client SMTP stabilisce una connessione **FTP** alla porta nota 25 con il server SMTP.

Dovrebbe essere TCP al posto di FTP.

**Comment by frjnn** [comment]
Grazie mille, corretto.
